# Generated by Django 3.1.2 on 2020-10-31 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Région')),
                ('class_name', models.CharField(max_length=10, verbose_name='Nom de la classe')),
                ('coord', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Département')),
                ('class_name', models.CharField(max_length=10, verbose_name='Nom de la classe')),
                ('coord', models.CharField(max_length=1000)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.region')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
    ]
