# Generated by Django 3.1.2 on 2020-10-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='coord',
            field=models.CharField(max_length=2000),
        ),
    ]
