# Generated by Django 3.1.2 on 2020-10-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20201031_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='coord',
            field=models.CharField(max_length=2000),
        ),
    ]
