# Generated by Django 3.1.2 on 2020-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20201031_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='viewbox',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
