# Generated by Django 3.1.2 on 2020-11-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20201108_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='article',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='url',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Titre'),
        ),
    ]
