# Generated by Django 3.1.2 on 2020-11-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20201109_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['title'], 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
    ]
